appium.server.url=http://127.0.0.1:4723
platform.name=Android
platform.version=17
device.name=emulator-5554
app.path=../app/build/outputs/apk/debug/app-debug.apk
app.package=com.neurobehavior.drift
app.activity=com.neurobehavior.drift.ui.MainActivity
explicit.wait=30
implicit.wait=2
